version: "3"

services:
  app:
    image: mavedb-api/mavedb-api:dev
    build:
      context: .
    command: bash -c "pytest tests/"
    depends_on:
      - db
      - seqrepo
    env_file:
      - settings/.env.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_DATABASE_NAME: postgres
    volumes:
      - ./tests/:/code/tests/:ro
      - mavedb-seqrepo-dev:/usr/local/share/seqrepo

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres

  seqrepo:
    image: biocommons/seqrepo:latest
    volumes:
      - mavedb-seqrepo-dev:/usr/local/share/seqrepo

volumes:
  mavedb-seqrepo-dev:
